export const milestoneNames = [
  'Shanna helps Afghanistan',
  'Pieda helps Albania',
  'Lisandr helps Algeria',
  'Lin helps Andorra',
  'Sau helps Angola',
  'Sofi helps Antigua & Deps',
  'Lorett helps Argentina',
  'Sophi helps Armenia',
  'Ler helps Australia',
  'Penn helps Austria',
  'Evely helps Azerbaijan',
  'Fann helps Bahamas',
  'Rick helps Bahrain',
  'Stace helps Bangladesh',
  'Suzi helps Barbados',
  'Nelso helps Belarus',
  'Tifan helps Belgium',
  'Jenn helps Belize',
  'Annett helps Benin',
  'Sulem helps Bhutan',
  'Osvald helps Bolivia',
  'Marylouis helps Bosnia Herzegovina',
  'Ja helps Botswana',
  'Sharlen helps Brazil',
  'Fond helps Brunei',
  'Clarett helps Bulgaria',
  'Jan helps Burkina',
  'Barr helps Burundi',
  'Ruthann helps Cambodia',
  'Elwoo helps Cameroon',
  'Audre helps Canada',
  'Tobi helps Cape Verde',
  'Cathi helps Central African Rep',
  'Sheb helps Chad',
  'Porsh helps Chile',
  'Jo helps China',
  'Maribet helps Colombia',
  'Shonn helps Comoros',
  'Shelto helps Congo',
  'Lisett helps Congo {Democratic Rep}',
  'Socorr helps Costa Rica',
  'Tris helps Croatia',
  'Pe helps Cuba',
  'Tanne helps Cyprus',
  'Laver helps Czech Republic',
  'Alain helps Denmark',
  'Lorenz helps Djibouti',
  'Kace helps Dominica',
  'Dariu helps Dominican Republic',
  'R helps East Timor',
  'Luther helps Ecuador',
  'Ariana helps Egypt',
  'Gilberte helps El Salvador',
  'Lyman helps Equatorial Guinea',
  'Piedad helps Eritrea',
  'Easter helps Estonia',
  'Ignacia helps Ethiopia',
  'Harry helps Fiji',
  'Benjamin helps Finland',
  'Samual helps France',
  'Jadwiga helps Gabon',
  'Dan helps Gambia',
  'Julienne helps Georgia',
  'Kayla helps Germany',
  'Ewa helps Ghana',
  'Sabina helps Greece',
  'Darline helps Grenada',
  'Ramiro helps Guatemala',
  'Ernestina helps Guinea',
  'Deandra helps Guinea-Bissau',
  'Lucienne helps Guyana',
  'Corina helps Haiti',
  'Candie helps Honduras',
  'Karoline helps Hungary',
  'Clayton helps Iceland',
  'Valrie helps India',
  'Waneta helps Indonesia',
  'Rosalind helps Iran',
  'Viola helps Iraq',
  'Chanel helps Ireland {Republic}',
  'Melvina helps Israel',
  'Olive helps Italy',
  'Waltraud helps Ivory Coast',
  'Matha helps Jamaica',
  'Gia helps Japan',
  'Raven helps Jordan',
  'Eufemia helps Kazakhstan',
  'Genesis helps Kenya',
  'Neoma helps Kiribati',
  'Sulema helps Korea North',
  'September helps Korea South',
  'Antwan helps Kosovo',
  'Kieth helps Kuwait',
  'Mendy helps Kyrgyzstan',
  'Lorina helps Laos',
  'Jamar helps Latvia',
  'Jeanett helps Lebanon',
  'Dessie helps Lesotho',
  'Jessi helps Liberia',
  'Patrihelps Libya',
  'Zachariah helps Liechtenstein',
  'Norbert helps Lithuania',
  'Kareem helps Luxembourg',
  'Minta helps Macedonia',
  'Brittany helps Madagascar',
  'Idalia helps Malawi',
  'Leandra helps Malaysia',
  'Olympia helps Maldives',
  'Bettie helps Mali',
  'Ai helps Malta',
  'Temika helps Marshall Islands',
  'Nicolas helps Mauritania',
  'Roseann helps Mauritius',
  'Kymberly helps Mexico',
  'Geraldine helps Micronesia',
  'Elayne helps Moldova',
  'Lindsey helps Monaco',
  'Margy helps Mongolia',
  'Shari helps Montenegro',
  'Nidia helps Morocco',
  'Andrew helps Mozambique',
  'Leia helps Myanmar, {Burma}',
  'Vivan helps Namibia',
  'Tuan helps Nauru',
  'Emory helps Nepal',
  'Britt helps Netherlands',
  'Oretha helps New Zealand',
  'Connie helps Nicaragua',
  'Alda helps Niger',
  'Christene helps Nigeria',
  'Kattie helps Norway',
  'Virgina helps Oman',
  'Hayley helps Pakistan',
  'Jannie helps Palau',
  'Iola helps Panama',
  'Marline helps Papua New Guinea',
  'Christeen helps Paraguay',
  'Johna helps Peru',
  'Reynaldo helps Philippines',
  'Dayna helps Poland',
  'Neoma helps Portugal',
  'Judson helps Qatar',
  'Jacquline helps Romania',
  'Trinity helps Russian Federation',
  'Margareta helps Rwanda',
  'Clora helps St Kitts & Nevis',
  'Elli helps St Lucia',
  'Kyla helps Saint Vincent & the Grenadines',
  'Jacqui helps Samoa',
  'Jinny helps San Marino',
  'Lewis helps Sao Tome & Principe',
  'Hannelore helps Saudi Arabia',
  'Dorsey helps Senegal',
  'Mirna helps Serbia',
  'Collin helps Seychelles',
  'Ross helps Sierra Leone',
  'Setsuko helps Singapore',
  'Claudette helps Slovakia',
  'Sebrina helps Slovenia',
  'Divina helps Solomon Islands',
  'Isabella helps Somalia',
  'Agripina helps South Africa',
  'Nga helps South Sudan',
  'Dora helps Spain',
  'Misty helps Sri Lanka',
  'Olivia helps Sudan',
  'Yoshie helps Suriname',
  'Tobi helps Swaziland',
  'Sena helps Sweden',
  'Tamatha helps Switzerland',
  'Stephani helps Syria',
  'Son helps Taiwan',
  'Charolette helps Tajikistan',
  'Candace helps Tanzania',
  'Fumiko helps Thailand',
  'Queenie helps Togo',
  'Anabel helps Tonga',
  'Winnifred helps Trinidad & Tobago',
  'Xiomara helps Tunisia',
  'Tegan helps Turkey',
  'Sharla helps Turkmenistan',
  'Jennie helps Tuvalu',
  'Kraig helps Uganda',
  'Garfield helps Ukraine',
  'Mayola helps United Arab Emirates',
  'Codi helps United Kingdom',
  'Mauro helps United States',
  'Adah helps Uruguay',
  'Velva helps Uzbekistan',
  'Sonya helps Vanuatu',
  'Tory helps Vatican City',
  'Cherryl helps Venezuela',
  'Yun helps Vietnam',
  'Tami helps Yemen',
  'Agueda helps Zambia',
  'Bernardina helps Zimbabwe'
]
